#spring.application.name=Local-Transport-Ticketing-System
spring:
  datasource:
    url: jdbc:mysql://localhost:3360/ticketing
    username: root
    password: jvman19
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        TYPE: TRACE
